### Obtener token primero
# @name login
POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
  "email": "franzz2000@mail.com",
  "password": "admin123"
}

### Guardar el token de la respuesta
@authToken = {{login.response.body.token}}

###
POST http://localhost:3001/api/reuniones
Authorization: Bearer {{authToken}}
  content-type: application/json

  {
    "fecha": "2025-06-14",
    "hora": "10:00",
    "ubicacion": "Casa de la Comunidad",
    "descripcion": "Reunion de la Comunidad",
    "grupo_id": 1
  }

###
GET http://localhost:3001/api/reuniones
Authorization: Bearer {{authToken}}

###
GET http://localhost:3001/api/usuarios
Authorization: Bearer {{authToken}}

###
POST http://localhost:3001/api/usuarios
Authorization: Bearer {{authToken}}
content-type: application/json

  {
    "nombre": "Fernando",
    "primer_apellido": "Zamora",
    "segundo_apellido": "Sánchez",
    "email": "franzz2000@gmail.com",
    "telefono": "123456789",
    "puesto_trabajo": "Desarrollador",
    "observaciones": "Reunion de la Comunidad"
  }

###
GET http://localhost:3001/api/miembros?grupoId=1&activo=true
Authorization: Bearer {{authToken}}

###
GET http://localhost:3001/api/reuniones/1/asistencias
Authorization: Bearer {{authToken}}